### ISSUE TITLE
Duplicate templates between ckanext-blob-storage and ckanext-datapub

### ISSUE THREAD

**Issue by shevron** [datopian/ckanext-datapub#8]
There are a few templates that are the same or very close between ckanext-blob-storage and this extension, and it's just confusing. 

If ckanext-blob-storage will always depend on datapub, and has no UI at all, the templates should be removed from there. But I don't like this solution cause it creates cyclical dependencies between these two extensions, and I think ckanext-blob-storage should have some kind of basic UI. So I suggest assuming the base templates exist in ckanext-blob-storage (as this extension has a dependency on it anyway) and removing the duplicates from here. 

You can then override only `templates/blob_storage/snippets/upload_module.html` to point to the right JS files, no need to also override `templates/package/*`.

**Comment by shevron** [comment]
Actually, I just found out that this extension also copies / overwrites some helpers from `ckanext-blob-storage`. I'm not sure why. There is probably a dependency anyway so why duplicate?

**Comment by anuveyatsu** [comment]
@shevron I think our initial plan was to enable `datapub` apps (React based) in CKAN so that projects that doesn't use `ckanext-blob-storage` can also use the new Dataset/Resource publishing apps. What is confusing is that we haven't explicitly stated it and the work wasn't completed.

I think our challenge here is to maintain this extension as a generic one so we can use it in different projects, however, so far we already have created a separate branch per project.
